In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [4]:
#読み込み
wine_data = pd.read_csv("train.tsv",delimiter='\t')
wine_test_data = pd.read_csv("test.tsv",delimiter='\t')

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [9]:
#モデル作成　評価
X = wine_data.drop(["id","Y"],axis=1)
Y = wine_data["Y"]

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [11]:
clf = RandomForestClassifier(n_estimators=1000,max_depth=3,random_state=0)

clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [13]:
#predict
result = clf.predict(X_test)

In [15]:
#score
score = clf.score(X_test,y_test)

print(score)

0.8888888888888888

In [16]:
y_test_data = wine_test_data.drop(["id"],axis=1)

In [17]:
result = clf.predict(y_test_data)

In [18]:
# 提出用に加工
np_id = wine_test_data['id'].values
dd=pd.DataFrame({"id":np_id, "ans":result})
dd.to_csv("result01_nomal.csv",header=False,index=False)
dd

     id  ans
0     2    1
1     4    3
2     5    2
3     7    2
4     8    1
5    10    1
6    16    2
7    18    2
8    19    1
9    22    2
10   24    1
11   26    3
12   27    1
13   30    2
14   33    3
15   37    1
16   40    3
17   43    2
18   44    3
19   45    2
20   50    3
21   51    2
22   54    2
23   55    2
24   56    2
25   59    2
26   60    3
27   61    3
28   62    2
29   63    3
..  ...  ...
59  122    2
60  123    1
61  124    1
62  125    1
63  126    2
64  129    1
65  131    1
66  134    1
67  135    1
68  138    3
69  141    2
70  144    3
71  145    1
72  146    2
73  151    2
74  155    3
75  156    1
76  158    1
77  159    2
78  160    2
79  161    3
80  162    2
81  163    1
82  164    1
83  166    2
84  168    1
85  170    2
86  171    3
87  174    2
88  175    2

[89 rows x 2 columns]

結果　94.3%